import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import AppSidebar from "@/components/app-sidebar";
import mongoose from "mongoose";
import { Page } from "@/models/page";
// import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }
  mongoose.connect(process.env.MONGO_URI);
  const page = await Page.findOne({ owner: session?.user?.email });

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="fixed -left-48 bottom-0 top-0 z-20 h-[1200px]  w-48 bg-gray-300 p-4 pt-6  shadow-lg shadow-black  transition-all md:static">
            <div className="sticky top-0 pt-2">
              <div className="mx-auto aspect-square w-24 overflow-hidden rounded-full">
                <Image
                  src={session.user.image}
                  width={256}
                  height={256}
                  alt={"avatar"}
                />
              </div>
              {page && (
                <div className="mt-4">
                  <h1 className="text-2xl font-bold">{page.displayName}</h1>
                  <p className="text-sm">{page.bio}</p>
                </div>
              )}
              <AppSidebar />
            </div>
          </aside>
          <div className="grow">
            <div className="m-4 bg-secondary p-4 shadow">{children}</div>
          </div>
        </main>

        <Toaster position="bottom-right" theme="light" richColors />
      </body>
    </html>
  );
}
