import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
// import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        > */}
        <Header />
        <main>{children}</main>
        {/* </ThemeProvider> */}
        <Toaster position="bottom-right" theme="light" richColors />
      </body>
    </html>
  );
}
